### ISSUE TITLE
CDG Video Not Scaling to Canvas

### ISSUE THREAD

**Issue by Tristan10** [bhj/cdgraphics#2]
I like this package, but I'm having trouble trying to give the player (canvas) dimensions. I'd like them to be responsive and for the CDG video to play within the bounds of the canvas. It seems like giving the canvas any height will cause the video to be scaled way beyond the limits of the canvas.

The dark blue square is the bounds of the canvas element. Is there any way to force the video to be within the bounds of the canvas element?

![image](https://user-images.githubusercontent.com/35972672/89115595-ba38a200-d44f-11ea-954d-7897190a27e4.png)

**Comment by bhj** [comment]
Thanks for the screenshot! Can you confirm which version you're on?

The player should respond to the width and height attributes of the canvas element, but things get unpredictable with canvases if CSS is used for sizing. Try using the attributes only, no size-related CSS, and the canvas should be properly filled within reason (4:3 aspect ratio will always be maintained)

**Comment by Tristan10** [comment]
Thanks for the quick reply. Can confirm I am on the latest version (5.0.0)

It looks like setting the attributes on the canvas element fixes the issue. I really wanted to have the canvas be responsive and fill all available space (100% height and width). I guess I could get creative with javascript and manually update the attributes if the screen size changes.

**Comment by bhj** [comment]
Thanks for confirming. Yep, changing the attrs with JS is the best (only?) solution.

Definitely ran into this myself before; should probably add a note about it!
